title: "Mainak Sarkar's Personal Website"
description: "Welcome to my personal webpage"
baseurl: ""  # The base URL if you are deploying to <username>.github.io (i.e. an empty string)

# Author settings
author:
  name: "Mainak Sarkar"
  avatar: "/assets/images/your-avatar.png"  # Place your image in /assets/images/ directory
  bio: "PhD Student in Computer Vision"
  location: "TAMU, USA"
  email: "your_email@example.com"
  twitter: your_twitter_handle  # optional
  github: masarkar-tamu

# Theme settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown options
markdown: kramdown
kramdown:
  input: GFM

# Permalinks
permalink: /:categories/:title/
